---
# Source: kd/charts/drive-ui/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: drive-ui
  labels:
    app.kubernetes.io/name: drive-ui
    helm.sh/chart: drive-ui-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drive-ui
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drive-ui
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: drive-ui
          image: "drivehub.azurecr.io/meateam/drive-ui:v2.3.1"
          envFrom:
          - configMapRef:
              name: kd.config
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          
          resources:
            limits:
              cpu: 1
              memory: 128Mi
            requests:
              cpu: 500m
              memory: 128Mi
            