---
# Source: kd/charts/authentication-service/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authentication-service
  labels:
    app.kubernetes.io/name: authentication-service
    helm.sh/chart: authentication-service-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*.northeurope.cloudapp.azure.com'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 5242880m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 1d
    nginx.ingress.kubernetes.io/proxy-read-timeout: 1d
    nginx.ingress.kubernetes.io/proxy-send-timeout: 1d
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
         
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /auth
            backend:
              serviceName: authentication-service
              servicePort: http