---
# Source: kd/charts/authentication-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app.kubernetes.io/name: authentication-service
    helm.sh/chart: authentication-service-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: authentication-service
    app.kubernetes.io/instance: release-name