dependencies:
  - name: drive-ui
    version: 0.1.0
    repository: file://../drive-ui
  - name: api-gateway
    version: 0.1.0
    repository: file://../api-gateway
  - name: dropbox-service
    version: 0.1.0
    repository: file://../dropbox-service
  - name: download-service
    version: 0.1.0
    repository: file://../download-service
  - name: upload-service
    version: 0.1.0
    repository: file://../upload-service
  - name: file-service
    version: 0.1.0
    repository: file://../file-service
  - name: authentication-service
    version: 0.1.0
    repository: file://../authentication-service
  - name: user-service
    version: 0.1.0
    repository: file://../user-service
  - name: permission-service
    version: 0.1.0
    repository: file://../permission-service
  - name: test-saml-idp
    version: 0.1.0
    repository: file://../test-saml-idp
  - name: redis
    version: 0.1.0
    repository: file://../redis
  - name: search-service
    version: 0.1.0
    repository: file://../search-service
  - name: spike-service
    version: 0.1.0
    repository: file://../spike-service
  - name: gotenberg
    version: 0.1.0
    repository: file://../gotenberg
