# Default values for server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "v1.2"

nameOverride: "spike-service"
fullnameOverride: "spike-service"
# deployment:
#   health:
#     enabled: true
#     checks:
#       livenessProbe:
#         httpGet:
#           path: /
#           port: 80
#         initialDelaySeconds: 30
#         periodSeconds: 15
#         timeoutSeconds: 1
#         successThreshold: 1
#         failureThreshold: 3
#       readinessProbe:
#         httpGet:
#           path: /
#           port: 80
#         initialDelaySeconds: 30
#         periodSeconds: 15
#         timeoutSeconds: 1
#         successThreshold: 1
#         failureThreshold: 3
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 100m
   memory: 1024Mi
  requests:
   cpu: 50m
   memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
