# Default values for server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "develop"

nameOverride: "quota-ui"
fullnameOverride: "quota-ui"
deployment:
  health:
    enabled: true
    checks:
      livenessProbe:
        httpGet:
          path: /quota-ui/isalive
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /quota-ui/isalive
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 1
   memory: 128Mi
  requests:
   cpu: 500m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
