---
# Source: kd/charts/gotenberg/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gotenberg
  labels:
    app.kubernetes.io/name: gotenberg
    helm.sh/chart: gotenberg-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gotenberg
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gotenberg
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: gotenberg
          image: "drivehub.azurecr.io/meateam/gotenberg:6"
          envFrom:
          - configMapRef:
              name: kd.config
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gotenberg-tmp-volume
              mountPath: /gotenberg/tmp
            - name: gotenberg-tmp-volume
              mountPath: /tmp
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi
            
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 2Gi
          name: gotenberg-tmp-volume
        
