---
# Source: kd/charts/gotenberg/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  labels:
    app.kubernetes.io/name: gotenberg
    helm.sh/chart: gotenberg-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/instance: release-name